# Generated by Django 2.2.10 on 2020-05-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0002_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='precio',
        ),
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
